[tools]
"cargo:topgrade" = "latest"
"pipx:yamlfix" = "latest"
bat = "latest"
bat-extras = "latest"
chezmoi = "latest"
dive = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
git = "latest"
go = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
krew = "latest"
kustomize = "latest"
neovim = "latest"
node = "latest"
oras = "latest"
pipx = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
tflint = "latest"
zoxide = "latest"


[settings]
idiomatic_version_file_enable_tools = ["terraform"]
experimental = true
python_compile = true
